hpo:
  direction: maximize
  objective: valid/acc
  sampler: tpe
  n_trials: 30

search_space:
  trainer.optimizer.lr: [loguniform, 0.01, 0.5]
  trainer.optimizer.weight_decay: [loguniform, 1e-6, 1e-3]
  trainer.batch_size: [choice, [128, 256, 384, 512]]
  trainer.lr_scheduler.warmup: [int, 0, 2000]
  trainer.label_smoothing: [uniform, 0.0, 0.2]

