model: yolo11s-seg.pt
run_name: yolo_seg_train
data_yaml: data/yolo_dataset_v1/data.yaml
seed: 42
train_args:
  epochs: 10
  batch: 4
  imgsz: 2048
  workers: 12
  cache: "disk"
  lr0: 0.012
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  dfl: 1.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.1
  close_mosaic: 10
  val: true
  save: true
  plots: true
  cos_lr: true
  overlap_mask: true
  mask_ratio: 4
  pretrained: true
  exist_ok: true
  amp: true
  save_period: -1
