dataset:
  name: cifar10
  root: ./data
  download: true
  batch_size: 256
  val_ratio: 0.05
  mean: [0.4914, 0.4822, 0.4465]
  std:  [0.2470, 0.2435, 0.2616]
  random_crop: true
  hflip: true
  autoaugment: false
  randaugment: false

