exp:
  name: cifar10_train
  dataset:
    name: cifar10
    batch_size: 128
  model:
    name: resnet50_tv
  trainer:
    name: sl
    epochs: 100
    batch_size: 128
    label_smoothing: 0.1
    max_grad_norm: 1.0
    optimizer:
      name: sgd
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
      nesterov: true
    lr_scheduler:
      name: cosine
      T_max: 45000
      warmup: 500

